### ISSUE TITLE
All your code is missing!

### ISSUE THREAD

**Issue by memo-saldana** [Loptt/dogs-page#1]
Looks like you haven't uploaded your code to the repo, you should start by doing that!

**Comment by codyvi** [comment]
I can assure you that today 21/04/2020, the code is still missing.

**Comment by Loptt** [comment]
Hi @memo-saldana , thanks for your comment! Indeed that was the case 5 days ago. Nonetheless, the code has been uploaded and now you can view a live demo of this page here:  https://loptt.github.io/dogs-page/

If you happen to have any more comments or suggestions please feel free to leave a comment.
